### ISSUE TITLE
setState warning

### ISSUE THREAD

**Issue by oyeanuj** [xuopled/react-google-maps-loader#16] opened 2018-04-05 18:46 UTC
Hi @xuopled, thank you open-sourcing this library - it's really useful.

I seem to get this error while using it:
```
warning.js:33 Warning: Can't call setState (or forceUpdate) on an unmounted component. 
This is a no-op, but it indicates a memory leak in your application.  To fix, cancel all subscriptions 
and asynchronous tasks in the componentWillUnmount method.
```

Any thoughts on what might be going on?

**Comment by xuopled** [comment] 2018-04-10 05:36
I could not reproduce but I published a new version using `componentDidMount` instead of `componentWillMount`. It should fix the warning. Please checkout the `v4.2.1`

**Comment by xuopled** [comment] 2018-04-17 07:39
I don't have any news from you. I will close the issue. Feel free to reopen if the bug is still here

**Closed by xuopled** 2018-04-17 07:39 UTC

**Comment by oyeanuj** [comment] 2018-04-20 17:56
@xuopled Thank you for the fix, I'll test again and let you know if it didn't fix it.
